name: Deploy Flask App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag & push Docker image to ECR
      run: |
        REPO="YOUR_ECR_REPO_NAME"
        IMAGE_TAG="latest"

        docker build -t $REPO:$IMAGE_TAG .
        docker tag $REPO:$IMAGE_TAG ${{ steps.ecr-login.outputs.registry }}/$REPO:$IMAGE_TAG
        docker push ${{ steps.ecr-login.outputs.registry }}/$REPO:$IMAGE_TAG

    - name: Deploy to EC2 over SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: EC2_PUBLIC_IP
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker stop flask-app || true
          sudo docker rm flask-app || true
          sudo docker pull ${{ steps.ecr-login.outputs.registry }}/YOUR_ECR_REPO_NAME:latest
          sudo docker run -d -p 5000:5000 --name flask-app \
            ${{ steps.ecr-login.outputs.registry }}/YOUR_ECR_REPO_NAME:latest
